### ISSUE TITLE
Preserve genotypes and other FORMAT fields

### ISSUE THREAD

**Issue by tskir** [EBIvariation/variant-remapping#10]
When the input VCF file has FORMAT/Sample columns they are not carried over to the output (rightly or wrongly, I don't know), but the FORMAT definition in the header was. That made `bcftools norm` seg fault.

_Originally posted by @tcezard in https://github.com/EBIvariation/variant-remapping/pull/9_

Currently we're removing FORMAT lines, but ideally we should carry everything over.

**Comment by tskir** [comment]
The way of reindexing alleles for the genotypes is described in the [Google Doc](https://docs.google.com/document/d/1ayfEPznvqkS3jKehaYH-jzFta9Rvrhqd_TK_ysT5uS8/) as well.

**Comment by tcezard** [comment]
This was done in #27
